name: 3D Isometric City

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: AryanPandeyDev
          template: classic
          base: "" # This turns off the standard stats so we just get the 3D city
          config_timezone: Asia/Kolkata
          
          # The 3D Calendar Settings
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Output file name
          filename: 3d-city.svg
